CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_updated_at ON conversations (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications (type);
CREATE INDEX IF NOT EXISTS idx_notifications_reference_id ON notifications (reference_id);
CREATE INDEX IF NOT EXISTS idx_connections_status ON connections (status);
CREATE INDEX IF NOT EXISTS idx_connections_created_at ON connections (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_connections_updated_at ON connections (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_status ON feedback (status);
CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON feedback (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_votes_created_at ON feedback_votes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_created_at ON security_events (created_at DESC);