CREATE INDEX IF NOT EXISTS idx_wis_chunks_updated_at ON wis_chunks (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_procedures_created_at ON wis_procedures (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_procedures_updated_at ON wis_procedures (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_parts_created_at ON wis_parts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_parts_updated_at ON wis_parts (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_sessions_user_id ON wis_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_wis_sessions_server_id ON wis_sessions (server_id);
CREATE INDEX IF NOT EXISTS idx_wis_sessions_status ON wis_sessions (status);
CREATE INDEX IF NOT EXISTS idx_wis_sessions_created_at ON wis_sessions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_sessions_updated_at ON wis_sessions (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_usage_logs_user_id ON wis_usage_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_wis_usage_logs_session_id ON wis_usage_logs (session_id);
CREATE INDEX IF NOT EXISTS idx_wis_usage_logs_created_at ON wis_usage_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_servers_status ON wis_servers (status);
CREATE INDEX IF NOT EXISTS idx_wis_servers_created_at ON wis_servers (created_at DESC);