-- U435 Maintenance Manual Database Entries
-- Generated for Barry AI Integration

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('maintenance', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('service', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('routine maintenance', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('general maintenance', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('general', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('inspection', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('check', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('adjustment', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('information', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('procedure', 'U435_Maint_00_General_Info.pdf', 'general'),
  ('maintenance', 'U435_Maint_00_Safety.pdf', 'general'),
  ('service', 'U435_Maint_00_Safety.pdf', 'general'),
  ('routine maintenance', 'U435_Maint_00_Safety.pdf', 'general'),
  ('general maintenance', 'U435_Maint_00_Safety.pdf', 'general'),
  ('inspection', 'U435_Maint_00_Safety.pdf', 'general'),
  ('safety', 'U435_Maint_00_Safety.pdf', 'general'),
  ('check', 'U435_Maint_00_Safety.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_00_Safety.pdf', 'general'),
  ('adjustment', 'U435_Maint_00_Safety.pdf', 'general'),
  ('procedures', 'U435_Maint_00_Safety.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_00_Safety.pdf', 'general'),
  ('procedure', 'U435_Maint_00_Safety.pdf', 'general'),
  ('maintenance', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('service', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('routine maintenance', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('general maintenance', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('general', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('inspection', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('check', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('adjustment', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('specifications', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('procedure', 'U435_Maint_00_Specifications.pdf', 'general'),
  ('maintenance', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('service', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('routine maintenance', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('general maintenance', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('general', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('inspection', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('check', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('adjustment', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('procedures', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('procedure', 'U435_Maint_00_General_Maintenance.pdf', 'general'),
  ('maintenance', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('service', 'U435_Maint_0_Foreward.pdf', 'general')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('routine maintenance', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('general maintenance', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('foreward', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('inspection', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('manual', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('check', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('adjustment', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('procedure', 'U435_Maint_0_Foreward.pdf', 'general'),
  ('maintenance', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('drive belts', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('engine mount', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('engine', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('engine housing', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('engine service', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('engine timing', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('housing', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('mount maintenance', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('timing maintenance', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('engine maintenance', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('belt system', 'U435_Maint_01_Engine_Housing.pdf', 'engine'),
  ('maintenance', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('drive belts', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('engine mount', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('timing', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('engine', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('engine housing', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('engine service', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('engine timing', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('mount maintenance', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('timing maintenance', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('engine maintenance', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('belt system', 'U435_Maint_05_Engine_Timing.pdf', 'engine'),
  ('maintenance', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('air filter maintenance', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('air filter replacement', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('injector', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('fuel system maintenance', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('fuel', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('fuel injector', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('fuel injection', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('air filter service', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('injector service', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('fuel injector maintenance', 'U435_Maint_07_Fuel_Injectors.pdf', 'fuel'),
  ('maintenance', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('air filter', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('air filter maintenance', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('filter', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('air filter replacement', 'U435_Maint_09_Air_Filter.pdf', 'fuel')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('fuel system maintenance', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('air', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('fuel injection', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('air filter service', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('air cleaner', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('injector service', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('fuel injector maintenance', 'U435_Maint_09_Air_Filter.pdf', 'fuel'),
  ('maintenance', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('hydraulic brake maintenance', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('mechanical brake maintenance', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('pedal linkage', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('compressed air system', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('compressor service', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('air compressor', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('compressed air', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('pneumatic brake maintenance', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('air', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('brake inspection', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('compressor', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('air compressor maintenance', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('brake maintenance', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('brake service', 'U435_Maint_13_Air_Compressor.pdf', 'brakes'),
  ('maintenance', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('drive belts', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('engine mount', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('belt tension adjustment', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('engine housing', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('engine service', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('belt', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('belt tension', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('system', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('engine timing', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('drive belt service', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('mount maintenance', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('timing maintenance', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('engine maintenance', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('belt maintenance', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('drive belt', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('belt system', 'U435_Maint_13_Belt_System.pdf', 'engine'),
  ('maintenance', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil maintenance', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil level check', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('lubrication system', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil filter', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('lubrication', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil service', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('engine lubrication', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('engine', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('lubrication maintenance', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil change procedure', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('oil change', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('engine oil', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil level', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('engine oil service', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('oil pump', 'U435_Maint_18_Engine_Lubrication.pdf', 'lubrication'),
  ('maintenance', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('drive belts', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('engine mount', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('engine', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('engine housing', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('engine service', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('engine timing', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('mount', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('mount maintenance', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('timing maintenance', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('engine maintenance', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('belt system', 'U435_Maint_24_Engine_Mounts.pdf', 'engine'),
  ('maintenance', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('transmission maintenance', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('clutch service', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('clutch', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('clutch pressure plate', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('clutch adjustment', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('transmission service', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('clutch maintenance', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('clutch disc', 'U435_Maint_25_Clutch.pdf', 'transmission'),
  ('maintenance', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('transmission oil', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('gearbox maintenance', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('transmission maintenance', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('clutch service', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('transmission', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('gearbox', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('transmission service', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('clutch maintenance', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('clutch adjustment', 'U435_Maint_26_Transmission.pdf', 'transmission'),
  ('maintenance', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('hydraulic brake maintenance', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('mechanical brake maintenance', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('linkage', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('pedal linkage', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('compressor service', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('pedal', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('pneumatic brake maintenance', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('brake inspection', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('air compressor maintenance', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('brake maintenance', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('brake service', 'U435_Maint_29_Pedal_Linkage.pdf', 'brakes'),
  ('maintenance', 'U435_Maint_31_Frame.pdf', 'general'),
  ('service', 'U435_Maint_31_Frame.pdf', 'general')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('routine maintenance', 'U435_Maint_31_Frame.pdf', 'general'),
  ('general maintenance', 'U435_Maint_31_Frame.pdf', 'general'),
  ('inspection', 'U435_Maint_31_Frame.pdf', 'general'),
  ('check', 'U435_Maint_31_Frame.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_31_Frame.pdf', 'general'),
  ('adjustment', 'U435_Maint_31_Frame.pdf', 'general'),
  ('frame', 'U435_Maint_31_Frame.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_31_Frame.pdf', 'general'),
  ('procedure', 'U435_Maint_31_Frame.pdf', 'general'),
  ('maintenance', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('suspension', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('suspension inspection', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('shock absorber maintenance', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('suspension maintenance', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('suspension service', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('shock absorber', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('spring', 'U435_Maint_32_Suspension.pdf', 'suspension'),
  ('maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front axle maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('drive shaft maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('wheel maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('rear axle maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front differential', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('axle maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front axle', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('prop shaft maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front axle service', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('axle', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front differential maintenance', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('front drive', 'U435_Maint_33_Front_Axle.pdf', 'axles'),
  ('maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear axle service', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('front axle maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('drive shaft maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('wheel maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear axle', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear axle maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('axle maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('prop shaft maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('axle', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear differential maintenance', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear drive', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('rear differential', 'U435_Maint_35_Rear_Axle.pdf', 'axles'),
  ('maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('front axle maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('drive shaft maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('wheel maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('rear axle maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('shafts', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('axle maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('prop shaft maintenance', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('wheels', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('prop', 'U435_Maint_40_Wheels_Prop_Shafts.pdf', 'axles'),
  ('hydraulic oil', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brake fluid', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brake inspection', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('hydraulic brakes', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brakes', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('hydraulic brake maintenance', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('mechanical brake maintenance', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('pedal linkage', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('hydraulic system', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('pneumatic brake maintenance', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('air compressor maintenance', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('compressor service', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('hydraulic', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brake cylinder', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('hydraulic pump', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brake bleeding', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('hydraulic brake service', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brake service', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('maintenance', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brake maintenance', 'U435_Maint_42_Brakes_Hydraulic.pdf', 'brakes'),
  ('brakes', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('hydraulic brake maintenance', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('maintenance', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('mechanical brake maintenance', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('pedal linkage', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('mechanical brakes', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('brake adjustment', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('mechanical', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('compressor service', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('brake cable', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('mechanical brake service', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('pneumatic brake maintenance', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('brake inspection', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('air compressor maintenance', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('brake maintenance', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('brake service', 'U435_Maint_42_Brakes_Mechanical.pdf', 'brakes'),
  ('brakes', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('hydraulic brake maintenance', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('maintenance', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('mechanical brake maintenance', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('pedal linkage', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('compressor service', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('air brake service', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('pneumatic brake maintenance', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('air brakes', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('pneumatic brakes', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('brake inspection', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('pneumatic', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('air compressor maintenance', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('brake maintenance', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('brake service', 'U435_Maint_43_Brakes_Pneumatic.pdf', 'brakes'),
  ('maintenance', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering wheel', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering service', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering adjustment', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering box', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering inspection', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering maintenance', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('steering', 'U435_Maint_46_Steering.pdf', 'steering'),
  ('maintenance', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('drive belts', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('exhaust', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('engine housing', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('engine service', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('engine timing', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('timing maintenance', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('mount maintenance', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('engine mount', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('engine maintenance', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('belt system', 'U435_Maint_49_Exhaust.pdf', 'engine'),
  ('maintenance', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('cooling system check', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('cooling system', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('cooling maintenance', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('radiator maintenance', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('coolant service', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('cooling system maintenance', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('coolant level', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('coolant', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('system', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('coolant replacement', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('coolant level check', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('cooling', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('thermostat', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('radiator', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('radiator service', 'U435_Maint_50_Cooling_System.pdf', 'cooling'),
  ('maintenance', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('headlight maintenance', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('electrical maintenance', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('electrical equipment', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('battery', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('battery service', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('battery check', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('battery maintenance', 'U435_Maint_54_Batteries.pdf', 'electrical'),
  ('equipment', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('maintenance', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic oil', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic system', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic equipment maintenance', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic service', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic pump', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('hydraulic system maintenance', 'U435_Maint_55_Hydraulic_Equipment.pdf', 'hydraulic'),
  ('equipment', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('electrical system maintenance', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('maintenance', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('headlight maintenance', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('electrical maintenance', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('electrical equipment', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('wiring', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('battery', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('battery service', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('electrical', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('battery maintenance', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('electrical service', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('electrical system', 'U435_Maint_55_Electrical_Equipment.pdf', 'electrical'),
  ('equipment', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('service', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('maintenance', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('routine maintenance', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('general maintenance', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('mechanical', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('inspection', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('check', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('preventive maintenance', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('adjustment', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('scheduled maintenance', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('procedure', 'U435_Maint_55_Mechanical_Equipment.pdf', 'general'),
  ('maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('body maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('door maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('structure', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('cab maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('body panel maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('interior maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('body service', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('cab', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('window maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('seat maintenance', 'U435_Maint_60_Cab_Structure.pdf', 'body'),
  ('maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('body maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('door maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('windows', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('cab maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('body panel maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body')
;

INSERT INTO u435_manual_index (term, chapter_filename, system_category) VALUES
  ('doors', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('interior maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('window maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('seat maintenance', 'U435_Maint_60_Doors_Windows.pdf', 'body'),
  ('maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('body maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('interior', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('seats', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('door maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('cab maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('body panel maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('interior maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('window maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('seat maintenance', 'U435_Maint_60_Seats_Interior.pdf', 'body'),
  ('maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('door', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('body maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('door maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('body', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('cab maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('body panel maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('panels', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('window', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('seat', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('body panel', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('interior maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('body service', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('cab', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('window maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('seat maintenance', 'U435_Maint_60_Body_Panels.pdf', 'body'),
  ('maintenance', 'U435_Maint_82_Headlights.pdf', 'electrical'),
  ('headlight maintenance', 'U435_Maint_82_Headlights.pdf', 'electrical'),
  ('electrical maintenance', 'U435_Maint_82_Headlights.pdf', 'electrical'),
  ('electrical equipment', 'U435_Maint_82_Headlights.pdf', 'electrical'),
  ('headlight', 'U435_Maint_82_Headlights.pdf', 'electrical'),
  ('battery service', 'U435_Maint_82_Headlights.pdf', 'electrical'),
  ('battery maintenance', 'U435_Maint_82_Headlights.pdf', 'electrical')
;