-- U435 Manual Index - Generated from comprehensive index system
-- Total sections: 63
-- Solves page mapping between original 1,185 pages and 67 split PDFs

INSERT INTO u435_manual_index (
  original_page,
  pdf_page,
  title,
  section_name,
  keywords,
  filename,
  manual_part_id,
  category,
  priority
) VALUES
(
    5,
    1,
    'G',
    'General 00',
    ARRAY['general', 'installation'],
    'U435_01_General.pdf',
    1,
    'general',
    'low'
  ),
(
    85,
    35,
    'E',
    'Removal and installation of engine/engine housing 01.8',
    ARRAY['removal', 'and', 'installation', 'engine', 'housing', 'assembly', 'disassembly', 'torque', 'pressure'],
    'U435_03_Cylinder_Head.pdf',
    3,
    'engine',
    'high'
  ),
(
    86,
    36,
    'A',
    'Air filter 09.8',
    ARRAY['air', 'filter', 'engine', 'installation'],
    'U435_03_Cylinder_Head.pdf',
    3,
    'general',
    'high'
  ),
(
    89,
    1,
    'T',
    'Turbocharger 09.13',
    ARRAY['turbocharger', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_04_Engine_Block.pdf',
    4,
    'general',
    'standard'
  ),
(
    101,
    13,
    'T',
    'Turbocharger 09.14',
    ARRAY['turbocharger', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_04_Engine_Block.pdf',
    4,
    'general',
    'standard'
  ),
(
    112,
    24,
    'A',
    'Air compressor/Belt drives 13',
    ARRAY['air', 'compressor', 'belt', 'drives', 'drive'],
    'U435_04_Engine_Block.pdf',
    4,
    'general',
    'low'
  ),
(
    113,
    25,
    'A',
    'Air compressor 13.8',
    ARRAY['air', 'compressor', 'installation', 'torque'],
    'U435_04_Engine_Block.pdf',
    4,
    'general',
    'low'
  ),
(
    121,
    33,
    'B',
    'Belt drive 13.14',
    ARRAY['belt', 'drive', 'hydraulic', 'torque', 'generator', 'steering'],
    'U435_04_Engine_Block.pdf',
    4,
    'general',
    'standard'
  ),
(
    129,
    3,
    'E',
    'Electrical system 15.8',
    ARRAY['electrical', 'system', 'engine', 'removal', 'installation', 'torque', 'generator', 'starter', 'alternator'],
    'U435_05_Lubrication.pdf',
    5,
    'electrical',
    'high'
  ),
(
    137,
    11,
    'E',
    'Engine lubrication 18.8',
    ARRAY['engine', 'lubrication', 'oil', 'assembly', 'disassembly', 'removal', 'installation', 'torque', 'pressure'],
    'U435_05_Lubrication.pdf',
    5,
    'engine',
    'high'
  ),
(
    159,
    15,
    'C',
    'Cooling units on engine 20.8',
    ARRAY['cooling', 'units', 'engine', 'removal', 'installation', 'torque'],
    'U435_06_Cooling_System.pdf',
    6,
    'engine',
    'high'
  ),
(
    163,
    1,
    'T',
    'Transmission 26',
    ARRAY['transmission', 'drive'],
    'U435_07_Fuel_System.pdf',
    7,
    'transmission',
    'low'
  ),
(
    174,
    12,
    'E',
    'Engine suspension 22.8',
    ARRAY['engine', 'suspension', 'removal', 'installation', 'torque'],
    'U435_07_Fuel_System.pdf',
    7,
    'engine',
    'high'
  ),
(
    179,
    17,
    'C',
    'Clutch 25',
    ARRAY['clutch', 'torque'],
    'U435_07_Fuel_System.pdf',
    7,
    'general',
    'low'
  ),
(
    188,
    26,
    'T',
    'Torque converter clutch 25.14',
    ARRAY['torque', 'converter', 'clutch', 'installation'],
    'U435_07_Fuel_System.pdf',
    7,
    'general',
    'low'
  ),
(
    196,
    34,
    'D',
    'Clutch 25.21',
    ARRAY['clutch', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_07_Fuel_System.pdf',
    7,
    'general',
    'standard'
  ),
(
    207,
    7,
    'M',
    'Main Transmission 26.13',
    ARRAY['main', 'transmission', 'axle', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_08_Exhaust_System.pdf',
    8,
    'transmission',
    'standard'
  ),
(
    208,
    8,
    'M',
    'Main Transmission 26.13 (Continued)',
    ARRAY['main', 'transmission', 'continued', 'oil', 'seal', 'assembly', 'disassembly', 'removal', 'installation'],
    'U435_08_Exhaust_System.pdf',
    8,
    'transmission',
    'standard'
  ),
(
    347,
    21,
    'P',
    'Power take-off transmission 26.20',
    ARRAY['power', 'take', 'off', 'transmission', 'engine', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_12_Front_Axle_Drive.pdf',
    12,
    'transmission',
    'high'
  ),
(
    381,
    17,
    'P',
    'PTO transmission 26.23',
    ARRAY['pto', 'transmission', 'engine', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_13_Rear_Axle_Drive.pdf',
    13,
    'transmission',
    'high'
  ),
(
    411,
    9,
    'P',
    'Power take-off 26.25',
    ARRAY['power', 'take', 'off', 'assembly', 'disassembly', 'installation', 'torque'],
    'U435_14_Wiring.pdf',
    14,
    'general',
    'standard'
  ),
(
    424,
    22,
    'P',
    'Power take-off 26.26',
    ARRAY['power', 'take', 'off', 'installation', 'torque'],
    'U435_14_Wiring.pdf',
    14,
    'general',
    'low'
  ),
(
    435,
    33,
    'P',
    'Pedal Linkage 29',
    ARRAY['pedal', 'linkage', 'clutch', 'brake'],
    'U435_14_Wiring.pdf',
    14,
    'general',
    'high'
  ),
(
    436,
    34,
    'C',
    'Clutch pedal 29.10',
    ARRAY['clutch', 'pedal', 'removal', 'installation', 'starter'],
    'U435_14_Wiring.pdf',
    14,
    'general',
    'low'
  ),
(
    450,
    10,
    'B',
    'Brake pedal 29.11',
    ARRAY['brake', 'pedal', 'removal', 'installation'],
    'U435_15_Instruments.pdf',
    15,
    'brakes',
    'high'
  ),
(
    462,
    22,
    'C',
    'Control 30.1',
    ARRAY['control', 'installation'],
    'U435_15_Instruments.pdf',
    15,
    'general',
    'low'
  ),
(
    468,
    1,
    'V',
    'Frame 31',
    ARRAY['frame'],
    'U435_16_Frame.pdf',
    16,
    'general',
    'low'
  ),
(
    483,
    16,
    'F',
    'Frame 31.3',
    ARRAY['frame', 'installation'],
    'U435_16_Frame.pdf',
    16,
    'general',
    'low'
  ),
(
    491,
    7,
    'S',
    'Springs and Suspension 32',
    ARRAY['springs', 'and', 'suspension'],
    'U435_17_Suspension.pdf',
    17,
    'suspension',
    'low'
  ),
(
    492,
    8,
    'S',
    'Spring 32.6',
    ARRAY['spring', 'installation'],
    'U435_17_Suspension.pdf',
    17,
    'general',
    'low'
  ),
(
    500,
    16,
    'S',
    'Spring 32.7',
    ARRAY['spring', 'installation'],
    'U435_17_Suspension.pdf',
    17,
    'general',
    'low'
  ),
(
    508,
    24,
    'S',
    'Shock Absorber 32.11',
    ARRAY['shock', 'absorber', 'installation'],
    'U435_17_Suspension.pdf',
    17,
    'general',
    'low'
  ),
(
    512,
    28,
    'T',
    'Torsion Bar, Stabilizer 32.21',
    ARRAY['torsion', 'bar', 'stabilizer', 'removal', 'installation', 'torque'],
    'U435_17_Suspension.pdf',
    17,
    'general',
    'standard'
  ),
(
    519,
    1,
    'F',
    'Front Axle 33',
    ARRAY['front', 'axle'],
    'U435_18_Steering.pdf',
    18,
    'axles',
    'low'
  ),
(
    555,
    1,
    'W',
    'Disassembly and Assembly of Wheel Hub Drive 33.3',
    ARRAY['disassembly', 'and', 'assembly', 'wheel', 'hub', 'drive', 'axle', 'brake', 'oil', 'seal'],
    'U435_19_Wheel_Hub_Front.pdf',
    19,
    'portal_hubs',
    'high'
  ),
(
    569,
    15,
    'F',
    'General 33.6',
    ARRAY['general', 'axle', 'wheel', 'hub', 'drive', 'differential', 'bearing', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_19_Wheel_Hub_Front.pdf',
    19,
    'general',
    'high'
  ),
(
    583,
    29,
    'F',
    'Removal and Installation of Front Axle 33.6',
    ARRAY['removal', 'and', 'installation', 'front', 'axle', 'wheel', 'nut'],
    'U435_19_Wheel_Hub_Front.pdf',
    19,
    'axles',
    'high'
  ),
(
    616,
    2,
    'R',
    'Rear axle 35.3',
    ARRAY['rear', 'axle'],
    'U435_21_Hub_Maintenance.pdf',
    21,
    'axles',
    'low'
  ),
(
    617,
    3,
    'R',
    'Rear Axle 35.3',
    ARRAY['rear', 'axle', 'wheel', 'hub', 'drive', 'differential', 'bearing', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_21_Hub_Maintenance.pdf',
    21,
    'axles',
    'high'
  ),
(
    651,
    1,
    'R',
    'Disassembly and Reassembly of Wheel Hub Drive 35.3',
    ARRAY['disassembly', 'and', 'reassembly', 'wheel', 'hub', 'drive', 'axle', 'brake', 'oil', 'seal', 'assembly'],
    'U435_22_Wheel_Hub_Rear.pdf',
    22,
    'portal_hubs',
    'high'
  ),
(
    661,
    11,
    'R',
    'General 35.6',
    ARRAY['general', 'axle', 'wheel', 'hub', 'drive', 'differential', 'bearing', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_22_Wheel_Hub_Rear.pdf',
    22,
    'general',
    'high'
  ),
(
    705,
    19,
    'W',
    'Wheels and tires 40.2',
    ARRAY['wheels', 'and', 'tires', 'wheel', 'pressure'],
    'U435_23_Service_Brakes.pdf',
    23,
    'general',
    'high'
  ),
(
    710,
    24,
    'B',
    'Brakes (Hydraulic) 42.11',
    ARRAY['brakes', 'hydraulic', 'axle', 'wheel', 'brake', 'seal', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_23_Service_Brakes.pdf',
    23,
    'brakes',
    'high'
  ),
(
    755,
    33,
    'B',
    'Brakes (Hydraulic) 42.14',
    ARRAY['brakes', 'hydraulic', 'axle', 'wheel', 'brake', 'seal', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_24_Parking_Brake.pdf',
    24,
    'brakes',
    'high'
  ),
(
    793,
    35,
    'B',
    'Brake System (Pneumatic) 43.11',
    ARRAY['brake', 'system', 'pneumatic', 'hydraulic', 'installation', 'pressure'],
    'U435_25_Main_Hydraulics.pdf',
    25,
    'brakes',
    'high'
  ),
(
    925,
    23,
    'S',
    'Steering 46',
    ARRAY['steering', 'nut'],
    'U435_29_HVAC_Heating.pdf',
    29,
    'steering',
    'low'
  ),
(
    926,
    24,
    'S',
    'Steering 46.11',
    ARRAY['steering', 'wheel', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_29_HVAC_Heating.pdf',
    29,
    'steering',
    'high'
  ),
(
    948,
    10,
    'S',
    'Steering 46.12',
    ARRAY['steering', 'wheel', 'assembly', 'disassembly', 'removal', 'installation', 'torque'],
    'U435_30_Lighting.pdf',
    30,
    'steering',
    'high'
  ),
(
    967,
    29,
    'P',
    'Power Steering Pump 46.23',
    ARRAY['power', 'steering', 'pump', 'oil', 'assembly', 'disassembly', 'removal', 'installation'],
    'U435_30_Lighting.pdf',
    30,
    'steering',
    'standard'
  ),
(
    982,
    8,
    'P',
    'Power Steering Pump 46.24',
    ARRAY['power', 'steering', 'pump', 'oil', 'installation'],
    'U435_31_Special_Equipment.pdf',
    31,
    'steering',
    'low'
  ),
(
    990,
    16,
    'E',
    'Electrical System 54.7',
    ARRAY['electrical', 'system', 'installation'],
    'U435_31_Special_Equipment.pdf',
    31,
    'electrical',
    'low'
  ),
(
    1017,
    1,
    'E',
    'Electrical System 54.12',
    ARRAY['electrical', 'system', 'installation'],
    'U435_32_Advanced_Electrical.pdf',
    32,
    'electrical',
    'low'
  ),
(
    1031,
    1,
    'E',
    'Electrical System 54.13',
    ARRAY['electrical', 'system', 'installation'],
    'U435_33_Box_Electrical.pdf',
    33,
    'electrical',
    'low'
  ),
(
    1037,
    1,
    'P',
    'PTO Shafts 55.002',
    ARRAY['pto', 'shafts', '002', 'installation'],
    'U435_34_PTO_Shafts.pdf',
    34,
    'general',
    'low'
  ),
(
    1042,
    1,
    'H',
    'Hydraulic System 55.102',
    ARRAY['hydraulic', 'system', '102', 'installation'],
    'U435_35_Hydraulic_Advanced.pdf',
    35,
    'hydraulics',
    'low'
  ),
(
    1052,
    1,
    'H',
    'Hydrostat 55.202',
    ARRAY['hydrostat', '202', 'transmission', 'oil', 'removal', 'installation'],
    'U435_36_Hydrostat_Trans.pdf',
    36,
    'general',
    'standard'
  ),
(
    1075,
    1,
    'D',
    'Driver''s Cab 60.5',
    ARRAY['driver', 'cab', 'drive', 'removal', 'installation', 'torque'],
    'U435_37_Driver_Cab_Tilt.pdf',
    37,
    'general',
    'standard'
  ),
(
    1095,
    1,
    'B',
    'Box-Type Body 60.12',
    ARRAY['box', 'type', 'body', 'removal', 'installation', 'torque'],
    'U435_38_Box_Body_System.pdf',
    38,
    'general',
    'standard'
  ),
(
    1124,
    1,
    'E',
    'Electrical System 82.12',
    ARRAY['electrical', 'system'],
    'U435_39_Headlight_System.pdf',
    39,
    'electrical',
    'low'
  ),
(
    1125,
    2,
    'E',
    'Electrical System 82.15',
    ARRAY['electrical', 'system', 'removal', 'installation'],
    'U435_39_Headlight_System.pdf',
    39,
    'electrical',
    'low'
  ),
(
    1140,
    1,
    'H',
    'Heating System 83.3',
    ARRAY['heating', 'system', 'removal', 'installation'],
    'U435_40_Heating_Basic.pdf',
    40,
    'general',
    'low'
  ),
(
    1152,
    1,
    'A',
    'Auxiliary Heater (Eberspächer V 7 S) 83.11',
    ARRAY['auxiliary', 'heater', 'ebersp', 'cher', 'gasket', 'removal', 'installation', 'temperature', 'generator'],
    'U435_41_Heater_Eberspacher.pdf',
    41,
    'general',
    'standard'
  ),
(
    1181,
    30,
    'H',
    'Renewing Heat Exchanger and Burner 83.11',
    ARRAY['renewing', 'heat', 'exchanger', 'and', 'burner', 'seal', 'temperature', 'electrical', 'generator'],
    'U435_41_Heater_Eberspacher.pdf',
    41,
    'general',
    'standard'
  );

-- Key Portal Hub Procedures (User's Primary Interest):
-- Front Portal Hub: Page 555 → U435_19_Wheel_Hub_Front.pdf page 1
-- Rear Portal Hub: Page 651 → U435_22_Wheel_Hub_Rear.pdf page 1

-- Index includes 63 sections with intelligent page mapping
-- Barry can now navigate users to exact PDF pages with proper context
