#!/bin/bash
# Git Safe Wrapper Functions
# Generated by git-audit
# Version: 1.0.0

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging function for wrappers
log_wrapper() {
    local level="$1"
    shift
    local message="$*"
    
    case "${level}" in
        "ERROR")
            echo -e "${RED}[GIT-SAFE-ERROR]${NC} ${message}" >&2
            ;;
        "WARN")
            echo -e "${YELLOW}[GIT-SAFE-WARN]${NC} ${message}" >&2
            ;;
        "INFO")
            echo -e "${BLUE}[GIT-SAFE-INFO]${NC} ${message}"
            ;;
        "SUCCESS")
            echo -e "${GREEN}[GIT-SAFE-SUCCESS]${NC} ${message}"
            ;;
    esac
}

# Safe lock file handling
wait_for_git_lock_release() {
    local lock_file="$1"
    local timeout="${2:-300}" # 5 minutes default
    local counter=0
    
    if [[ ! -f "$lock_file" ]]; then
        return 0
    fi
    
    log_wrapper "INFO" "Waiting for lock file to be released: $lock_file"
    
    while [[ -f "$lock_file" && $counter -lt $timeout ]]; do
        # Check if lock is stale (older than 1 hour)
        if command -v stat >/dev/null 2>&1; then
            local lock_age
            if stat -f%m "$lock_file" >/dev/null 2>&1; then
                # macOS stat
                local lock_time=$(stat -f%m "$lock_file")
                local current_time=$(date +%s)
                lock_age=$((current_time - lock_time))
            else
                # Linux stat
                local lock_time=$(stat -c%Y "$lock_file")
                local current_time=$(date +%s)
                lock_age=$((current_time - lock_time))
            fi
            
            # Remove stale locks (older than 1 hour)
            if [[ $lock_age -gt 3600 ]]; then
                log_wrapper "WARN" "Removing stale lock file (${lock_age}s old): $lock_file"
                rm -f "$lock_file"
                return 0
            fi
        fi
        
        if [[ $((counter % 30)) -eq 0 ]]; then
            log_wrapper "INFO" "Still waiting for lock release... (${counter}s)"
        fi
        
        sleep 1
        ((counter++))
    done
    
    if [[ -f "$lock_file" ]]; then
        log_wrapper "ERROR" "Timeout waiting for lock file release: $lock_file"
        return 1
    fi
    
    log_wrapper "SUCCESS" "Lock file released: $lock_file"
    return 0
}

# Safe git reset with backup
safe_git_reset_hard() {
    local target="${1:-HEAD}"
    local backup_ref="refs/git-safe-backup/reset-$(date +%s)"
    
    log_wrapper "INFO" "Performing safe git reset --hard to $target"
    
    # Create backup reference
    if git update-ref "$backup_ref" HEAD 2>/dev/null; then
        log_wrapper "SUCCESS" "Created backup reference: $backup_ref"
    else
        log_wrapper "WARN" "Could not create backup reference"
    fi
    
    # Wait for any lock files
    local git_dir=$(git rev-parse --git-dir)
    for lock_file in "$git_dir"/*.lock; do
        [[ -f "$lock_file" ]] && wait_for_git_lock_release "$lock_file"
    done
    
    # Perform reset
    if git reset --hard "$target"; then
        log_wrapper "SUCCESS" "Git reset completed successfully"
        log_wrapper "INFO" "Backup available at: $backup_ref"
        return 0
    else
        log_wrapper "ERROR" "Git reset failed"
        return 1
    fi
}

# Safe git clean with confirmation
safe_git_clean() {
    local force_flag="${1:-}"
    
    log_wrapper "INFO" "Performing safe git clean"
    
    # Show what would be removed first
    log_wrapper "INFO" "Files that would be removed:"
    git clean -dn
    
    if [[ "$force_flag" != "--force" ]]; then
        echo -n "Are you sure you want to remove these files? (y/N): "
        read -r response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            log_wrapper "INFO" "Git clean cancelled by user"
            return 0
        fi
    fi
    
    # Wait for lock files
    local git_dir=$(git rev-parse --git-dir)
    for lock_file in "$git_dir"/*.lock; do
        [[ -f "$lock_file" ]] && wait_for_git_lock_release "$lock_file"
    done
    
    # Perform clean
    if git clean -fd; then
        log_wrapper "SUCCESS" "Git clean completed successfully"
        return 0
    else
        log_wrapper "ERROR" "Git clean failed"
        return 1
    fi
}

# Safe force push with protection
safe_git_force_push() {
    local remote="${1:-origin}"
    local branch="${2:-$(git branch --show-current)}"
    local force_flag="${3:-}"
    
    log_wrapper "INFO" "Performing safe force push to $remote/$branch"
    
    # Check if this is a protected branch
    local protected_branches="main master production release"
    for protected in $protected_branches; do
        if [[ "$branch" == "$protected" ]] && [[ "$force_flag" != "--allow-protected" ]]; then
            log_wrapper "ERROR" "Force push to protected branch '$branch' blocked"
            log_wrapper "INFO" "Use --allow-protected flag to override"
            return 1
        fi
    done
    
    # Show what will be pushed
    log_wrapper "INFO" "Commits to be force-pushed:"
    git log --oneline "$remote/$branch..HEAD" 2>/dev/null || git log --oneline -n 5
    
    if [[ "$force_flag" != "--force" ]]; then
        echo -n "Are you sure you want to force push? (y/N): "
        read -r response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            log_wrapper "INFO" "Force push cancelled by user"
            return 0
        fi
    fi
    
    # Use --force-with-lease for safety
    if git push --force-with-lease "$remote" "$branch"; then
        log_wrapper "SUCCESS" "Safe force push completed"
        return 0
    else
        log_wrapper "ERROR" "Force push failed"
        return 1
    fi
}

# Execute git command with proper error handling
git_command_with_error_handling() {
    local git_cmd="$*"
    local git_dir=$(git rev-parse --git-dir 2>/dev/null || echo "")
    
    # Wait for lock files if in a git repository
    if [[ -n "$git_dir" ]]; then
        for lock_file in "$git_dir"/*.lock; do
            [[ -f "$lock_file" ]] && wait_for_git_lock_release "$lock_file"
        done
    fi
    
    # Execute git command with error handling
    local start_time=$(date +%s)
    if git $git_cmd; then
        local end_time=$(date +%s)
        local duration=$((end_time - start_time))
        log_wrapper "SUCCESS" "Git command completed successfully (${duration}s): git $git_cmd"
        return 0
    else
        local exit_code=$?
        log_wrapper "ERROR" "Git command failed (exit code: $exit_code): git $git_cmd"
        return $exit_code
    fi
}

# Check if Git operation is safe to perform
check_git_operation_safety() {
    local operation="$1"
    
    # Check if we're in a git repository
    if ! git rev-parse --git-dir >/dev/null 2>&1; then
        log_wrapper "ERROR" "Not in a git repository"
        return 1
    fi
    
    # Check for existing lock files
    local git_dir=$(git rev-parse --git-dir)
    local active_locks=()
    
    for lock_file in "$git_dir"/*.lock; do
        if [[ -f "$lock_file" ]]; then
            active_locks+=("$(basename "$lock_file")")
        fi
    done
    
    if [[ ${#active_locks[@]} -gt 0 ]]; then
        log_wrapper "WARN" "Active Git locks detected: ${active_locks[*]}"
        log_wrapper "INFO" "Waiting for locks to be released..."
        
        for lock_file in "${active_locks[@]}"; do
            wait_for_git_lock_release "$git_dir/$lock_file"
        done
    fi
    
    # Check repository integrity before risky operations
    local risky_ops="reset|rebase|filter-branch|gc"
    if echo "$operation" | grep -qE "$risky_ops"; then
        log_wrapper "INFO" "Checking repository integrity before risky operation..."
        if ! git fsck --no-progress >/dev/null 2>&1; then
            log_wrapper "ERROR" "Repository integrity check failed"
            log_wrapper "INFO" "Run 'git fsck --full' to diagnose issues"
            return 1
        fi
    fi
    
    return 0
}

# Export functions for use in other scripts
export -f wait_for_git_lock_release
export -f safe_git_reset_hard
export -f safe_git_clean
export -f safe_git_force_push
export -f git_command_with_error_handling
export -f check_git_operation_safety
