-- WIS Fake Data Cleanup Script
-- Purpose: Remove ALL fake data generated by previous AI attempts
-- Date: October 13, 2025
-- WARNING: This will delete ALL current WIS data. Only real data from Codex extraction will remain.

-- ============================================================================
-- STEP 1: DISABLE ROW LEVEL SECURITY (Temporarily)
-- ============================================================================

ALTER TABLE wis_chunks DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedures DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_steps DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_parts DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_tools DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_relationships DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_parts DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_parts_catalog DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_service_bulletins DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_bulletins DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_bulletin_procedures DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_components DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_systems DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_models DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_tools DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_diagrams DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_media_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE wis_wiring DISABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 2: TRUNCATE ALL WIS TABLES (Cascading Delete)
-- ============================================================================

-- Core data tables
TRUNCATE TABLE wis_chunks CASCADE;
TRUNCATE TABLE wis_procedures CASCADE;
TRUNCATE TABLE wis_procedure_steps CASCADE;
TRUNCATE TABLE wis_procedure_parts CASCADE;
TRUNCATE TABLE wis_procedure_tools CASCADE;
TRUNCATE TABLE wis_procedure_relationships CASCADE;
TRUNCATE TABLE wis_parts CASCADE;
TRUNCATE TABLE wis_parts_catalog CASCADE;
TRUNCATE TABLE wis_service_bulletins CASCADE;
TRUNCATE TABLE wis_bulletins CASCADE;
TRUNCATE TABLE wis_bulletin_procedures CASCADE;
TRUNCATE TABLE wis_tools CASCADE;
TRUNCATE TABLE wis_diagrams CASCADE;
TRUNCATE TABLE wis_media_files CASCADE;
TRUNCATE TABLE wis_wiring CASCADE;

-- Hierarchy tables
TRUNCATE TABLE wis_components CASCADE;
TRUNCATE TABLE wis_systems CASCADE;
TRUNCATE TABLE wis_models CASCADE;

-- ============================================================================
-- STEP 3: RE-ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE wis_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_procedure_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_parts_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_service_bulletins ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_bulletins ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_bulletin_procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_diagrams ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_media_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE wis_wiring ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 4: VERIFY CLEANUP (All counts should be 0)
-- ============================================================================

SELECT 'wis_chunks' as table_name, COUNT(*) as count FROM wis_chunks
UNION ALL
SELECT 'wis_procedures', COUNT(*) FROM wis_procedures
UNION ALL
SELECT 'wis_procedure_steps', COUNT(*) FROM wis_procedure_steps
UNION ALL
SELECT 'wis_parts', COUNT(*) FROM wis_parts
UNION ALL
SELECT 'wis_service_bulletins', COUNT(*) FROM wis_service_bulletins
UNION ALL
SELECT 'wis_components', COUNT(*) FROM wis_components
UNION ALL
SELECT 'wis_systems', COUNT(*) FROM wis_systems
UNION ALL
SELECT 'wis_models', COUNT(*) FROM wis_models
ORDER BY table_name;

-- Expected output: All tables should show count = 0

-- ============================================================================
-- STEP 5: CLEANUP STORAGE BUCKET (Optional - requires manual action)
-- ============================================================================

-- Note: Storage bucket cleanup must be done via Supabase dashboard or API
-- Navigate to: Storage → wis-docs
-- Delete all files except:
-- - model/U435/procedures/unimog_400_oil_change.html (if you want to keep sample)
-- - model/U435/bulletins/tsb_2020_001_portal_axle.html (if you want to keep sample)
-- - model/U435/parts/unimog_portal_axle_parts.json (if you want to keep sample)

-- ============================================================================
-- COMPLETION LOG
-- ============================================================================

-- Log this cleanup operation
INSERT INTO wis_etl_logs (
  operation_type,
  status,
  message,
  created_at
) VALUES (
  'CLEANUP_FAKE_DATA',
  'COMPLETED',
  'Removed all fake data generated by previous AI attempts. Database ready for real Codex extraction.',
  NOW()
);

-- ============================================================================
-- DONE!
-- ============================================================================

-- Your database is now clean and ready for real Mercedes WIS data import.
-- Next steps:
-- 1. Run Codex extraction following CODEX_EXTRACTION_INSTRUCTIONS.md
-- 2. Verify Codex deliverables using CODEX_VERIFICATION_CHECKLIST.md
-- 3. Import real data using ETL processor
