CREATE INDEX IF NOT EXISTS idx_community_posts_category ON community_posts (category);
CREATE INDEX IF NOT EXISTS idx_pending_manual_uploads_category ON pending_manual_uploads (category);
CREATE INDEX IF NOT EXISTS idx_processed_manuals_category ON processed_manuals (category);
CREATE INDEX IF NOT EXISTS idx_reddit_articles_category ON reddit_articles (category);
CREATE INDEX IF NOT EXISTS idx_trip_emergency_alerts_severity ON trip_emergency_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_wis_bulletins_category ON wis_bulletins (category);
CREATE INDEX IF NOT EXISTS idx_wis_bulletins_severity ON wis_bulletins (severity);
CREATE INDEX IF NOT EXISTS idx_wis_bulletins_status ON wis_bulletins (status);
CREATE INDEX IF NOT EXISTS idx_wis_diagrams_type ON wis_diagrams (type);
CREATE INDEX IF NOT EXISTS idx_community_posts_category_created ON community_posts (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trip_emergency_alerts_severity_created ON trip_emergency_alerts (severity, created_at DESC);