CREATE INDEX IF NOT EXISTS idx_posts_user_created ON posts (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post_created ON comments (post_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_post_comments_post_created ON post_comments (post_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_category_status ON marketplace_listings (category, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_seller_status ON marketplace_listings (seller_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vehicles_user_created ON vehicles (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fuel_logs_vehicle_created ON fuel_logs (vehicle_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_maintenance_logs_vehicle_created ON maintenance_logs (vehicle_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_procedures_category_created ON wis_procedures (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wis_parts_category_created ON wis_parts (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_community_recommendations_category_featured ON community_recommendations (category, is_featured, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_aggregated_content_category_created ON aggregated_content (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_interactions_user_content ON content_interactions (user_id, content_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_saved_content_user_created ON saved_content (user_id, created_at DESC);